version: "3.8"
services:
  temperature_db:
    image: "sumanta97/temperature_prediction:timescale_DB"
    volumes:
      - /home/sumanta/Realtime_Weather_Application/timescale_DB_hosting/app_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  data_fetch_api:
    image: "sumanta97/temperature_prediction:live_data_fetching_api"

  grafana:
    image: "grafana/grafana:8.2.6"
    command: bash -c "docker login -u docker_hub_id -p Password && /run.sh"
    ports:
      - "5433:3000"
    volumes:
      - /home/sumanta/Realtime_Weather_Application/grafana_hosting/app_data:/var/lib/grafana
    user: "root:root"


